# Generated by Django 5.2.8 on 2025-11-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('MAQUINARIA', 'Maquinaria')], max_length=20)),
                ('anio', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'vehiculo',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('destino', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.vehiculo')),
            ],
            options={
                'db_table': 'movimiento_carga',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
