# Generated by Django 5.2.8 on 2025-11-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='anio',
            new_name='año',
        ),
    ]
