# Generated by Django 5.2.8 on 2025-11-24 16:17

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_anio_vehiculo_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, unique=True, validators=[gestion.models.validar_patente]),
        ),
    ]
