# Generated by Django 5.2.8 on 2025-11-25 00:21

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_vehiculo_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocarga',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientocarga',
            name='destino',
            field=models.CharField(blank=True, help_text='Lugar de destino', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientocarga',
            name='fecha_hora',
            field=models.DateTimeField(help_text='Fecha y hora del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientocarga',
            name='origen',
            field=models.CharField(blank=True, help_text='Lugar de origen', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientocarga',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], help_text='Tipo de movimiento: Ingreso o Salida', max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientocarga',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo que realiza el movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(help_text='Año de fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del vehículo (Volvo, Ford, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del vehículo', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(help_text='Formato: 4 letras + 2 números (Ej: ABCD12)', max_length=6, unique=True, validators=[gestion.models.validar_patente]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('MAQUINARIA', 'Maquinaria')], help_text='Tipo de vehículo', max_length=20),
        ),
    ]
